#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/ProductKG/services/ProductKG/sparql

#+ summary: Retrieves all label for a given EAN
#+ tags: 
#+ - label
#+ - ByEAN

PREFIX lbl: <http://purl.org/ProductKG/label#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT ?name ?label WHERE {
	?product gr:name ?name.
    ?product gr:hasEAN_UCC-13 ?_EAN.
	?product lbl:has_label ?label.
  } 
