#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/ProductKG/services/ProductKG/sparql

#+ summary: Retrieves shelf location for new products of type medication that do not contain glutamate
#+ tags: 
#+ - location
#+ - flag
#+ - ingredients

PREFIX in: <http://purl.org/ProductKG/nonfoodingredient#>
PREFIX loc: <http://purl.org/ProductKG/location#>
PREFIX lbl: <http://purl.org/ProductKG/label#>
PREFIX tax: <http://purl.org/ProductKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT ?name ?shelf ?shelf_floor WHERE {
  ?product gr:name ?name.
  ?product in:has_ingredient ?ingredient.
  ?ingredient rdf:type ?inclass.
  FILTER(?inclass != in:Glutamate)
  ?product rdf:type tax:medication.
  ?product loc:has_flag "NEU".
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
} GROUP BY ?shelf
