#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/ProductKG/services/ProductKG/sparql

#+ summary: Retrieves shelf location for cheapest juice without sweetener
#+ tags: 
#+ - location
#+ - ingredients
#+ - price
#+ no entries for the price


PREFIX in: <http://purl.org/ProductKG/nonfoodingredient#>
PREFIX loc: <http://purl.org/ProductKG/location#>
PREFIX tax: <http://purl.org/ProductKG/product-taxonomy#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>

SELECT ?name ?shelf ?shelf_floor ?price WHERE {
  ?product gr:name ?name.
  ?product in:has_ingredient ?ingredient.
  ?ingredient rdf:type ?inclass.
  FILTER(?inclass != in:Sweetener)
  ?product rdf:type tax:juice.
  ?product loc:has_price ?price.
  ?product loc:stored_in ?shelf.
  ?product loc:stored_on ?shelf_floor.
} ORDER BY ?price
